import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Navbar from "@/components/Navbar";
import Providers from "@/Providers";
import SessionWrapper from "@/components/SessionWrapper"; // Import the client component

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <SessionWrapper>
            <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
              <Navbar /> {/* Wrap children with SessionWrapper */}
              <Providers>{children}</Providers>
            </div>
          </SessionWrapper>
        </SessionProvider>
      </body>
    </html>
  );
}
